// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmMDbVrQi4a43OR6ZzhkHuvnRYxhzFZM4',
    appId: '1:327027256225:web:c4099b829438ae287b39e0',
    messagingSenderId: '327027256225',
    projectId: 'projectbuddy-8607c',
    authDomain: 'projectbuddy-8607c.firebaseapp.com',
    storageBucket: 'projectbuddy-8607c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi1mIPQ7K1ww2-SngszGXV3WWiVY3GcrY',
    appId: '1:327027256225:android:97db4afe34dc7e3e7b39e0',
    messagingSenderId: '327027256225',
    projectId: 'projectbuddy-8607c',
    storageBucket: 'projectbuddy-8607c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvHx9xHa8ygAKUFGjvyl7uEiTl63Y3fi4',
    appId: '1:327027256225:ios:3406f02569af49267b39e0',
    messagingSenderId: '327027256225',
    projectId: 'projectbuddy-8607c',
    storageBucket: 'projectbuddy-8607c.firebasestorage.app',
    iosBundleId: 'com.example.medicareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvHx9xHa8ygAKUFGjvyl7uEiTl63Y3fi4',
    appId: '1:327027256225:ios:3406f02569af49267b39e0',
    messagingSenderId: '327027256225',
    projectId: 'projectbuddy-8607c',
    storageBucket: 'projectbuddy-8607c.firebasestorage.app',
    iosBundleId: 'com.example.medicareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcB2eEhhN4FdvfkbpDEsVHhpvb5iwcWOI',
    appId: '1:327027256225:web:05802a5dd17f25ef7b39e0',
    messagingSenderId: '327027256225',
    projectId: 'projectbuddy-8607c',
    authDomain: 'projectbuddy-8607c.firebaseapp.com',
    storageBucket: 'projectbuddy-8607c.firebasestorage.app',
  );
}
